'use client';
import {useRef,useState} from 'react';
import {Upload,Sparkles,ScanFace,Maximize,Eraser,Shirt,Download,WandSparkles} from 'lucide-react';
const toolList=[['Amélioration Pro',Sparkles,'Lumière, netteté et couleurs'],['Préserver le visage',ScanFace,'Identité et traits naturels'],['Upscale 4K',Maximize,'Plus de détails, haute résolution'],['Arrière-plan',Eraser,'Suppression et PNG transparent'],['T-shirt Ready',Shirt,'Fichier propre pour impression']];
type Item={file:File;src:string;result?:string;status:'ready'|'processing'|'done'|'error';error?:string};
export default function Home(){
 const input=useRef<HTMLInputElement>(null);const [items,setItems]=useState<Item[]>([]);const [active,setActive]=useState('Amélioration Pro');const [busy,setBusy]=useState(false);
 const pick=(list:FileList|File[])=>{const fs=Array.from(list).filter(f=>f.type.startsWith('image/')).slice(0,10);setItems(fs.map(file=>({file,src:URL.createObjectURL(file),status:'ready'})))};
 const processOne=async(it:Item,i:number)=>{setItems(x=>x.map((v,k)=>k===i?{...v,status:'processing'}:v));try{const fd=new FormData();fd.append('image',it.file);fd.append('tool',active);const r=await fetch('/api/enhance',{method:'POST',body:fd});const ct=r.headers.get('content-type')||'';const raw=await r.text();let d:any={};if(ct.includes('application/json')){try{d=JSON.parse(raw)}catch{throw new Error('Réponse JSON invalide du serveur')}}else{throw new Error(r.status===413?'Photo trop volumineuse pour le serveur. Essayez une image plus petite.':r.status>=500?'Le serveur photo est temporairement indisponible. Réessayez dans un instant.':'Réponse inattendue du serveur ('+r.status+').')}if(!r.ok||!d.image)throw new Error(d.error||'Traitement impossible');setItems(x=>x.map((v,k)=>k===i?{...v,status:'done',result:d.image}:v))}catch(e:any){setItems(x=>x.map((v,k)=>k===i?{...v,status:'error',error:e.message}:v))}};
 const processAll=async()=>{setBusy(true);for(let i=0;i<items.length;i++)await processOne(items[i],i);setBusy(false)};
 const download=(url:string,name:string)=>{const a=document.createElement('a');a.href=url;a.download='NovaPhoto-'+name.replace(/\.[^.]+$/,'')+'.png';a.click()};
 return <main><nav><b><i>✦</i> NovaPhoto <span>AI</span></b><div><a href="#studio">Studio</a><a href="#features">Outils</a><a href="/pricing">Tarifs</a><a href="/dashboard"><button>Se connecter</button></a></div></nav>
 <section className="hero"><div className="badge">✦ STUDIO PHOTO PROPULSÉ PAR L’IA</div><h1>Transformez vos photos<br/><em>en qualité professionnelle.</em></h1><p>Traitez une photo ou jusqu’à 10 images en même temps, avec priorité à la conservation naturelle des visages.</p><button className="primary" onClick={()=>input.current?.click()}><WandSparkles/> Ajouter des photos</button><small>JPG · PNG · WEBP — jusqu’à 10 photos par lot</small></section>
 <section id="studio" className="studio"><aside><h3>Outils IA</h3>{toolList.map(([n,I,d]:any)=><button key={n} className={active===n?'selected':''} onClick={()=>setActive(n)}><I/><span><strong>{n}</strong><small>{d}</small></span></button>)}</aside><div className="work"><div className="worktop"><span><b>{active}</b><small> · Batch jusqu’à 10 · Face Preserve</small></span><span className="credits">{items.length}/10 photos</span></div>
 {!items.length?<div className="drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files)}}><div className="upload"><Upload/></div><h2>Déposez vos photos ici</h2><p>Sélectionnez jusqu’à 10 images</p><button>Choisir des photos</button></div>:<><div className="grid">{items.map((it,i)=><article key={it.src} style={{overflow:'hidden'}}><img src={it.result||it.src} alt={it.file.name} style={{width:'100%',height:220,objectFit:'cover',borderRadius:12}}/><h3>{it.file.name}</h3><p>{it.status==='ready'?'Prête':it.status==='processing'?'Traitement en cours…':it.status==='done'?'Terminée ✓':it.error||'Erreur'}</p>{it.result&&<button onClick={()=>download(it.result!,it.file.name)}><Download/> Télécharger</button>}</article>)}</div><div className="actions"><button onClick={()=>input.current?.click()}>Changer les photos</button><button className="primary" onClick={processAll} disabled={busy}><Sparkles/> {busy?'Traitement du lot…':`Améliorer ${items.length} photo${items.length>1?'s':''}`}</button></div></>}
 <input ref={input} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files&&pick(e.target.files)}/></div></section>
 <section id="features" className="features"><h2>Un studio complet. <em>Une seule application.</em></h2><div className="grid">{toolList.map(([n,I,d]:any)=><article key={n}><I/><h3>{n}</h3><p>{d}. Traitement conçu pour un résultat naturel et professionnel.</p></article>)}</div></section><section className="pricing"><h2>Batch Processing intégré</h2><p>Importez jusqu’à 10 photos et traitez-les dans le même lot.</p><button className="primary" onClick={()=>input.current?.click()}>Essayer maintenant</button></section><footer><b>✦ NovaPhoto AI</b><span>Vos photos. Votre identité. Sublimées.</span></footer></main>
}